version: "3.7"

services:
    mongo:
        image: mongo:4
        container_name: test_mongoose_db
        hostname: aggregate-in-node-mongodb-driver
        env_file:
            - ./.env
        ports:
            - "$MONGODB_EXPOSED_PORT:27017"
