version: "3.7"

services:
    mongo:
        image: bitnami/mongodb:4.4-debian-10
        container_name: test_mongoose_db
        hostname: $APP_NAME
        env_file:
            - ./.env
        ports:
            - "$MONGODB_EXPOSED_PORT:27017"
